name: Next.js deployment

on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build

      - name: deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrete.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrete.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrete.AWS_REGION }}

      - name: deploy to s3
        run: aws s3 sync ./${{ secrete.BUILD_DIRECTORY }} ${{ secrete.AWS_S3_BUCKET_NAME }} --acl public-read --delete

      - name: CloudFront Invalidate Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrete.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
